[2021-12-17 15:33:47,132] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2021-12-16T00:00:00+00:00 [queued]>
[2021-12-17 15:33:47,144] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.accurate scheduled__2021-12-16T00:00:00+00:00 [queued]>
[2021-12-17 15:33:47,144] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-17 15:33:47,144] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-12-17 15:33:47,144] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-17 15:33:47,161] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): accurate> on 2021-12-16 00:00:00+00:00
[2021-12-17 15:33:47,162] {standard_task_runner.py:52} INFO - Started process 12887 to run task
[2021-12-17 15:33:47,169] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'accurate', 'scheduled__2021-12-16T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpz_lr_dvy', '--error-file', '/tmp/tmpige8j551']
[2021-12-17 15:33:47,170] {standard_task_runner.py:77} INFO - Job 17: Subtask accurate
[2021-12-17 15:33:47,200] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate scheduled__2021-12-16T00:00:00+00:00 [running]> on host sofienkhanfir-VirtualBox
[2021-12-17 15:33:47,238] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2021-12-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-16T00:00:00+00:00
[2021-12-17 15:33:47,239] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-12-17 15:33:47,241] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2021-12-17 15:33:47,253] {subprocess.py:85} INFO - Output:
[2021-12-17 15:33:47,253] {subprocess.py:89} INFO - accurate
[2021-12-17 15:33:47,253] {subprocess.py:93} INFO - Command exited with return code 0
[2021-12-17 15:33:47,274] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20211216T000000, start_date=20211217T143347, end_date=20211217T143347
[2021-12-17 15:33:47,306] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-12-17 15:33:47,329] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
